// Generated by CoffeeScript 1.4.0
var myApp;

if (!(window.console && console.log)) {
  (function() {
    var console, len, methods, noop, _results;
    noop = function() {};
    methods = ['assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error', 'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log', 'markTimeline', 'profile', 'profileEnd', 'markTimeline', 'table', 'time', 'timeEnd', 'timeStamp', 'trace', 'warn'];
    len = methods.length;
    console = window.console = {};
    _results = [];
    while (len--) {
      _results.push(console[methods[len]] = noop);
    }
    return _results;
  })();
}

/* --------------------------------------------
     Begin app.coffee
--------------------------------------------
*/


myApp = angular.module('myApp', []);

/* --------------------------------------------
     Begin directives.coffee
--------------------------------------------
*/


/* --------------------------------------------
     Begin filters.coffee
--------------------------------------------
*/


/* --------------------------------------------
     Begin services.coffee
--------------------------------------------
*/


/* --------------------------------------------
     Begin controllers.coffee
--------------------------------------------
*/


myApp.controller('MainAppCtrl', [
  '$scope', function($scope) {
    return $scope.title = "ng-Bootstrap";
  }
]);
