// Generated by CoffeeScript 1.4.0
var app, express, http, less, mongoose;

express = require('express');

mongoose = require('mongoose');

http = require('http');

less = require('less-middleware');

app = express();

app.locals.lessVersions = require('./lessVersions')['lessVersions'];

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set('views', "" + __dirname + "/views");
  app.set('view engine', 'jade');
  app.use(express.favicon());
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(less({
    src: "" + __dirname + "/public"
  }));
  app.use(express["static"]("" + __dirname + "/public"));
  return app.use(function(req, res) {
    res.status(404);
    if (req.accepts('html')) {
      return res.render("404", {
        title: 'LESS2CSS | 404'
      });
    } else if (req.accepts('json')) {
      return res.send({
        error: 'Not Found'
      });
    } else {
      return res.type('txt').send('404 Not Found');
    }
  });
});

app.get('/', function(req, res) {
  return res.render('less2css', {
    title: 'LESS2CSS | LESS Live Preview'
  });
});

http.createServer(app).listen(app.get('port'), function() {
  return console.log("Server started on port " + (app.get('port')));
});
