// Generated by CoffeeScript 1.4.0
var app, express, http, less, mongoose, routes;

express = require('express');

mongoose = require('mongoose');

routes = require('./routes');

http = require('http');

less = require('less-middleware');

app = express();

app.locals.lessVersions = require('./lessVersions')['lessVersions'];

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set('views', "" + __dirname + "/views");
  app.set('view engine', 'jade');
  app.use(express.favicon());
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(less({
    src: "" + __dirname + "/public"
  }));
  app.use(express["static"]("" + __dirname + "/public"));
  return app.use(function(req, res) {
    return res.send(404, "Four - Oh - Four");
  });
});

app.get('/', function(req, res) {
  return res.render('less2css', {
    title: 'LESS2CSS | LESS Live Preview'
  });
});

http.createServer(app).listen(app.get('port'), function() {
  return console.log("Server started on port " + (app.get('port')));
});
